### ISSUE TITLE
^M characters in panelfix.sh

### ISSUE THREAD

**Issue by interfect** [Nevax07/BootloaderChanger-g2#3]
I just tried flashing this on my LS980 to install the bumped LP bootloader and bumped patched recovery. I got "BootloaderChanger-LS980-nevax-2.1.2.zip" from MEGA.

The GUI hangs at "Flash LP Bunped Bootloader". When I go in with adb shell, folloowing along with the source, it looks like it flashes all the bootloader imgs and gets stuck trying to do the recovery (`/tmp` has `panelfix.sh` and `panelfix/recovery.img` laying around in it). When I try to `sh /tmp/panelfix.sh`, I get:

```
: not foundix.sh line 6:
: not foundix.sh line 16:
: not foundix.sh line 17:
/tmp.panelfix.sh: line 22: syntax error: unexpected "elif" (expecting "then")
```

Opening up `panelfix.sh` I see a `^M` at the end of every line, including blank lines.

So it looks like `panelfix.sh` has Windows line endings (with the carriage return character), and the shell on my phone is thinking `^M` on a blank line is a command and trying to run it, and it is also somehow interfering with the `if` statement syntax. The script crashes out and doesn't install the new recovery. I think it needs to be run through `dos2unix` or something to fix it up to unix line endings.

I manually removed the ^M characters with `vi` on the phone, and the script ran through just fine and installed the recovery. I will now see if said recovery works.

Thank you for this useful tool!

**Comment by agravelot** [comment]
Thank you very much, you just certainly solve the problem I could not fix.
I changed editing software (ATOM) and has converted all my files in dos at the beginning nothing worked.
:100:
